services:
  - type: web
    name: chdlm-mini-dashboard-app
    repo: https://github.com/ydrolet/chdlm-mini-dashboard
    branch: main
    rootDir: app
    runtime: static
    buildCommand: corepack enable; yarn install; yarn generate
    staticPublishPath: ./.output/public
    domains:
      - app.coopdelamontagne.com
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
      - key: ENVIRONMENT
        value: production
  - type: web
    name: chdlm-mini-dashboard-server
    repo: https://github.com/ydrolet/chdlm-mini-dashboard
    branch: main
    rootDir: server
    runtime: python
    buildCommand: poetry install
    startCommand: fastapi run --port 10000
    plan: starter
    region: virginia
    domains:
      - api.coopdelamontagne.com
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: POETRY_VERSION
        value: 1.8.3
      - key: SUPABASE_PROJECT_URL
        sync: false
      - key: SUPABASE_API_KEY
        sync: false
      - key: SUPABASE_SERVICE_ACCOUNT_JWT
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_NAME
        value: Comité de Participation
      - key: FROM_EMAIL_ADDRESS
        value: participation@coopdelamontagne.com
      - key: REPLY_TO_EMAIL_ADDRESS
        sync: false
