// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-axios';
import type { SendInvolvementSummaryEmailData, SendInvolvementSummaryEmailError, SendInvolvementSummaryEmailResponse, GetMembersListError, GetMembersListResponse, GetInfoError, GetInfoResponse } from './types.gen';

export const client = createClient(createConfig());

export class CommandService {
    /**
     * Send Involvement Summary Email
     */
    public static sendInvolvementSummaryEmail<ThrowOnError extends boolean = false>(options: Options<SendInvolvementSummaryEmailData, ThrowOnError>) {
        return (options?.client ?? client).post<SendInvolvementSummaryEmailResponse, SendInvolvementSummaryEmailError, ThrowOnError>({
            ...options,
            url: '/command/send-email'
        });
    }
    
}

export class DataService {
    /**
     * Get Members List
     */
    public static getMembersList<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetMembersListResponse, GetMembersListError, ThrowOnError>({
            ...options,
            url: '/data/members'
        });
    }
    
}

export class InfoService {
    /**
     * Get Info
     */
    public static getInfo<ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) {
        return (options?.client ?? client).get<GetInfoResponse, GetInfoError, ThrowOnError>({
            ...options,
            url: '/info/'
        });
    }
    
}