// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InfoSchema = {
    properties: {
        minPrecedingMonths: {
            type: 'integer',
            title: 'Minprecedingmonths'
        },
        maxPrecedingMonths: {
            type: 'integer',
            title: 'Maxprecedingmonths'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['minPrecedingMonths', 'maxPrecedingMonths'],
    title: 'Info'
} as const;

export const SendInvolvementSummaryEmailSchema = {
    properties: {
        memberFullName: {
            type: 'string',
            title: 'Memberfullname'
        },
        precedingMonths: {
            type: 'integer',
            maximum: 24,
            minimum: 3,
            title: 'Precedingmonths'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['memberFullName', 'precedingMonths'],
    title: 'SendInvolvementSummaryEmail'
} as const;

export const SendInvolvementSummaryEmailResultSchema = {
    properties: {
        memberFullName: {
            type: 'string',
            title: 'Memberfullname'
        },
        precedingMonths: {
            type: 'integer',
            maximum: 24,
            minimum: 3,
            title: 'Precedingmonths'
        },
        maskedEmailAddress: {
            type: 'string',
            format: 'email',
            title: 'Maskedemailaddress'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['memberFullName', 'precedingMonths', 'maskedEmailAddress'],
    title: 'SendInvolvementSummaryEmailResult'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;