// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Info = {
    minPrecedingMonths: number;
    maxPrecedingMonths: number;
};

export type SendInvolvementSummaryEmail = {
    memberFullName: string;
    precedingMonths: number;
};

export type SendInvolvementSummaryEmailResult = {
    memberFullName: string;
    precedingMonths: number;
    maskedEmailAddress: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type SendInvolvementSummaryEmailData = {
    body: SendInvolvementSummaryEmail;
};

export type SendInvolvementSummaryEmailResponse = (SendInvolvementSummaryEmailResult);

export type SendInvolvementSummaryEmailError = (HTTPValidationError);

export type GetMembersListResponse = (Array<(string)>);

export type GetMembersListError = unknown;

export type GetInfoResponse = (Info);

export type GetInfoError = unknown;